repos:
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: black (python)
        args:
          - '--target-version=py311'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: '(\.patch|\.diff|\.fasta$|\.fastq$|\.sam$|\.rbt$|\.bit$|target/)'
      - id: trailing-whitespace
        exclude: '(target/|\.patch|\.diff|\.fasta$|\.fastq$|\.sam$|\.rbt$|\.bit$)'
